# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hamiltonian Monte Carlo within Augmented Gibbs sampler for the GSPM model
#'
#' TBA
#'
#' @param K Number of components or subtypes
#' @param alpha Hyperparameter for the Dirichlet prior
#' @param lambda Variance smoothing parameter for the normal prior
#' @param gamma_shape Shape of the Gamma prior on the variance parameter for the data generating normal
#' @param gamma_rate Rate of the Gamma prior on the variance parameter for the data generating normal
#' @param max_iter Maximum number of iterations for the HMC within AGS algorithm
#' @param epsilon The step size of the HMC leep-frog iteration
#' @param Y The data matrix, an \code{n_samples x M} matrix, where \code{n_samples} is the
#'          number of observations and \code{M} is the number of features or
#'          genes
#' @param verbose 0 - no output; 1 - some output; 2 - more output
#'
#' @note
#' Author: Clint P. George
#'
#' License: GPL-3
#'
#' @family mcmc
#'
#' @export
gspm_ags_hmc <- function(K, alpha, lambda, sigma, sample_sigma, sigma_update_iter, gamma_shape, gamma_rate, max_iter, epsilon, Y, verbose) {
    .Call('gspm_gspm_ags_hmc', PACKAGE = 'gspm', K, alpha, lambda, sigma, sample_sigma, sigma_update_iter, gamma_shape, gamma_rate, max_iter, epsilon, Y, verbose)
}

#' Hamiltonian Monte Carlo within Augmented Gibbs sampler for Gaussian
#' Shrinkage Partial Membership models
#'
#' A GSPM model is indexed by scalar parameters K, alpha, lambda, and sigma
#'
#' @param K Number of components or subtypes
#' @param alpha Hyperparameter for the Dirichlet prior
#' @param lambda Variance smoothing parameter for the normal prior
#' @param sigma Variance parameter for the data generating normal
#' @param max_iter Maximum number of iterations for the HMC within AGS
#'                 algorithm
#' @param epsilon The step size of the HMC leep-frog iteration
#' @param Y The data matrix, an \code{n_samples x M} matrix, where
#'          \code{n_samples} is the number of observations and \code{M} is the
#'          number of features or genes
#' @param verbose 0 - no output; 1 - some output; 2 - more output
#'
#' @note
#' Author: Clint P. George
#'
#' License: GPL-3
#'
#' @family mcmc
#'
#' @export
spmm_ags_hmc <- function(K, alpha, lambda, sigma, max_iter, epsilon, Y, verbose) {
    .Call('gspm_spmm_ags_hmc', PACKAGE = 'gspm', K, alpha, lambda, sigma, max_iter, epsilon, Y, verbose)
}

#' Draw sample from the Generalized Inverse Gaussian (GIG) distribution.
#'
#'
#'
#' @param n sample size (positive integer)
#' @param lambda parameter for distribution
#' @param chi parameter for distribution
#' @param psi parameter for distribution
#'
#' @return random sample of size 'n'
#'
#' @export
#'
#' @family utils
#'
#' @note Adapted from the R package GIGrvg.
#'
#' All rights reserved with the R packge authors:
#' Josef Leydold and Wolfgang Hörmann.
#'
#'
#'
arma_rgig <- function(n, lambda, chi, psi) {
    .Call('gspm_arma_rgig', PACKAGE = 'gspm', n, lambda, chi, psi)
}

#' Samples from the Antoniak distribution
#'
#' It's done by sampling \eqn{N} Bernoulli variables
#'
#' References:
#'
#'   http://www.jmlr.org/papers/volume10/newman09a/newman09a.pdf
#'
#' @param N Number of samples
#' @param alpha strength parameter
#'
#' @export
#'
#' @family utils
#'
#' @note
#'
#' Created on: May 19, 2016
#'
#' Created by: Clint P. George
#'
sample_antoniak <- function(N, alpha) {
    .Call('gspm_sample_antoniak', PACKAGE = 'gspm', N, alpha)
}

sample_uniform_int <- function(K) {
    .Call('gspm_sample_uniform_int', PACKAGE = 'gspm', K)
}

#' A speedy sampling from a multimomial distribution
#'
#' @param theta a multinomial probability vector (K x 1 vector)
#'
#' @return returns a class index from [0, K)
#'
#' @note
#' Author: Clint P. George
#'
#' Created on: February 11, 2016
#'
#' @family utils
#'
#' @export
sample_multinomial <- function(theta) {
    .Call('gspm_sample_multinomial', PACKAGE = 'gspm', theta)
}

#' Samples from a Dirichlet distribution given a hyperparameter
#'
#' @param num_elements the dimention of the Dirichlet distribution
#' @param alpha the hyperparameter vector (a column vector)
#'
#' @return returns a Dirichlet sample (a column vector)
#'
#' @note
#' Author: Clint P. George
#'
#' Created on: 2014
#'
#' @family utils
#'
#' @export
sample_dirichlet <- function(num_elements, alpha) {
    .Call('gspm_sample_dirichlet', PACKAGE = 'gspm', num_elements, alpha)
}

#' Generating a multivariate gaussian distribution using RcppArmadillo
#'
#' There are many ways to simulate a multivariate gaussian distribution
#' assuming that you can simulate from independent univariate normal
#' distributions. One of the most popular method is based on the Cholesky
#' decomposition.
#'
#' @param n - the number of samples
#' @param mu - the mean vector
#' @param sigma - the covariace matrix
#'
#' @note
#' Author: Ahmadou Dicko — written Mar 12, 2013
#' License: GPL
#'
#' Reference:
#' http://gallery.rcpp.org/articles/simulate-multivariate-normal/
#'
#' @export
arma_mvrnorm <- function(n, mu, sigma) {
    .Call('gspm_arma_mvrnorm', PACKAGE = 'gspm', n, mu, sigma)
}

